### ISSUE TITLE
Getting "Unexpected token u in JSON at position 0" when ran POST request in POSTMAN

### ISSUE THREAD

**Issue by kanujbhatnagar** [chialab/math-api#2]
I get the following error when I execute the sample POST request provided, in POSTMAN:

`
{
    "message": "Unexpected token u in JSON at position 0"
}
`

Request:

> 
> POST /render HTTP/1.1
> Host: localhost:3000
> Accept: image/svg+xml
> Content-Type: application/json
> User-Agent: PostmanRuntime/7.15.0
> Cache-Control: no-cache
> Postman-Token: 2971d956-b4a9-43df-90d6-1d690b16c83f,d6ca15e5-1546-48c6-a7ec-04662a8d0286
> Host: localhost:3000
> accept-encoding: gzip, deflate
> content-length: 60
> Connection: keep-alive
> cache-control: no-cache
> 
> {
>   "input": "latex",
>   "output": "svg",
>   "source": "x^2"
> }
> 

I searched around and it seems that the 'u' in because 'undefined' is being returned. Can I print the entire debug message to see what's going wrong?

**Comment by fquffio** [comment]
Hi @kanujbhatnagar ! I tried to run the very same POST request you tried via cURL, and it works for me:

![image](https://user-images.githubusercontent.com/7108146/59996588-0a451280-965b-11e9-9e4e-7a5fd3ba62c0.png)

I assume you've started a local development server via `yarn run api-gateway`. Have you installed all required dependencies first (`yarn install; make layer`)?

**Comment by kanujbhatnagar** [comment]
I have this running on docker. Attaching my curl response.
![Screenshot 2019-06-24 at 13 20 39](https://user-images.githubusercontent.com/29087567/60000998-13e27080-9683-11e9-9af1-1b5d48b73a7c.png)

**Comment by fquffio** [comment]
Hmmm… 🤔 Can you tell me how you've built your Docker image?

**Comment by fquffio** [comment]
Ok, @kanujbhatnagar, I was eventually able to reproduce. Sorry for the issue, I'll try to address it right now!

**Comment by fquffio** [comment]
@kanujbhatnagar I've opened a Pull Request to address this issue. Do you have some time to run a couple of tests and/or leave a code review? 🙏 Don't worry if you can't. Thanks in advance!
