### ISSUE TITLE
Getting region error when executing Cloudformation stack

### ISSUE THREAD

**Issue by kanujbhatnagar** [chialab/math-api#9]
I get this error from AWS:

`Error occurred while GetObject. S3 Error Code: PermanentRedirect. S3 Error Message: The bucket is in this region: eu-west-1. Please use this region to retry the request (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 98fee368-384d-4ea6-8e39-e32cac3e5803)`

I'm trying to create the stack in the us-east-1 region.

@fquffio any thoughts?

**Comment by fquffio** [comment]
Ouch… you're right. We package the stack only on our bucket in `eu-west-1` (Ireland) 'cause it's the one we're using, but CloudFormation assumes the template is stored in a S3 bucket in the same region as the stack being created.

The quicker solution for you is to run `aws cloudformation package` yourself. There is already a Makefile in the repository root for that.
Assuming you have AWS CLI installed and a `default` profile, create a S3 bucket in `us-east-1` (N. Virginia) or use an existing bucket, then run these commands:

```console
$ make layers # This will install Node dependencies
$ make package PACKAGE_PROFILE=default PACKAGE_BUCKET=yourbucketname
```

The first command also requires Docker installed on your local machine. 😞 
The latter will output an URL in the form `https://yourbucketname.s3.amazonaws.com/blahblahblah/template.yml`, which you should then use to create the CloudFormation stack.

Let me know if this works for you. I'm keeping this issue open anyway in order to find a more reliable solution… probably we should package the template to more regions, although with new AWS regions being opened every now and then it would be a little troublesome to maintain properly.

**Comment by kanujbhatnagar** [comment]
`make layers` output:

> kanujbhatnagar@linux:~/math-api$ make layers
> docker run --rm \
> 	-v /home/kanujbhatnagar/math-api/layers/mathjax-node-layer/nodejs:/var/task \
> 	-e NODE_ENV=production \
> 	lambci/lambda:build-nodejs8.10 \
> 	npm  rebuild
> 
> > phantomjs-prebuilt@2.1.16 install /var/task/node_modules/phantomjs-prebuilt
> > node install.js
> 
> Found PhantomJS at /var/task/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs ...verifying
> PhantomJS is previously installed at /var/task/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs
> mathjax-node@2.1.1 /var/task/node_modules/mathjax-node
> is-fullwidth-code-point@2.0.0 /var/task/node_modules/is-fullwidth-code-point
> jsdom@11.12.0 /var/task/node_modules/jsdom
> abab@2.0.0 /var/task/node_modules/abab
> acorn@5.7.3 /var/task/node_modules/acorn
> acorn-globals@4.3.2 /var/task/node_modules/acorn-globals
> acorn@6.4.1 /var/task/node_modules/acorn-globals/node_modules/acorn
> acorn-walk@6.1.1 /var/task/node_modules/acorn-walk
> array-equal@1.0.0 /var/task/node_modules/array-equal
> cssom@0.3.6 /var/task/node_modules/cssom
> cssstyle@1.2.2 /var/task/node_modules/cssstyle
> data-urls@1.1.0 /var/task/node_modules/data-urls
> whatwg-mimetype@2.3.0 /var/task/node_modules/whatwg-mimetype
> whatwg-url@7.0.0 /var/task/node_modules/data-urls/node_modules/whatwg-url
> lodash.sortby@4.7.0 /var/task/node_modules/lodash.sortby
> tr46@1.0.1 /var/task/node_modules/tr46
> punycode@2.1.1 /var/task/node_modules/punycode
> webidl-conversions@4.0.2 /var/task/node_modules/webidl-conversions
> domexception@1.0.1 /var/task/node_modules/domexception
> escodegen@1.11.1 /var/task/node_modules/escodegen
> esprima@3.1.3 /var/task/node_modules/esprima
> estraverse@4.2.0 /var/task/node_modules/estraverse
> esutils@2.0.2 /var/task/node_modules/esutils
> optionator@0.8.2 /var/task/node_modules/optionator
> deep-is@0.1.3 /var/task/node_modules/deep-is
> fast-levenshtein@2.0.6 /var/task/node_modules/fast-levenshtein
> levn@0.3.0 /var/task/node_modules/levn
> prelude-ls@1.1.2 /var/task/node_modules/prelude-ls
> type-check@0.3.2 /var/task/node_modules/type-check
> wordwrap@1.0.0 /var/task/node_modules/wordwrap
> html-encoding-sniffer@1.0.2 /var/task/node_modules/html-encoding-sniffer
> whatwg-encoding@1.0.5 /var/task/node_modules/whatwg-encoding
> iconv-lite@0.4.24 /var/task/node_modules/iconv-lite
> safer-buffer@2.1.2 /var/task/node_modules/safer-buffer
> left-pad@1.3.0 /var/task/node_modules/left-pad
> nwsapi@2.1.4 /var/task/node_modules/nwsapi
> parse5@4.0.0 /var/task/node_modules/parse5
> pn@1.1.0 /var/task/node_modules/pn
> request@2.88.0 /var/task/node_modules/request
> aws-sign2@0.7.0 /var/task/node_modules/aws-sign2
> aws4@1.8.0 /var/task/node_modules/aws4
> caseless@0.12.0 /var/task/node_modules/caseless
> combined-stream@1.0.7 /var/task/node_modules/combined-stream
> delayed-stream@1.0.0 /var/task/node_modules/delayed-stream
> extend@3.0.2 /var/task/node_modules/extend
> forever-agent@0.6.1 /var/task/node_modules/forever-agent
> form-data@2.3.3 /var/task/node_modules/form-data
> asynckit@0.4.0 /var/task/node_modules/asynckit
> mime-types@2.1.24 /var/task/node_modules/mime-types
> mime-db@1.40.0 /var/task/node_modules/mime-db
> har-validator@5.1.3 /var/task/node_modules/har-validator
> ajv@6.10.0 /var/task/node_modules/ajv
> fast-deep-equal@2.0.1 /var/task/node_modules/fast-deep-equal
> fast-json-stable-stringify@2.0.0 /var/task/node_modules/fast-json-stable-stringify
> json-schema-traverse@0.4.1 /var/task/node_modules/json-schema-traverse
> uri-js@4.2.2 /var/task/node_modules/uri-js
> har-schema@2.0.0 /var/task/node_modules/har-schema
> http-signature@1.2.0 /var/task/node_modules/http-signature
> assert-plus@1.0.0 /var/task/node_modules/assert-plus
> jsprim@1.4.1 /var/task/node_modules/jsprim
> extsprintf@1.3.0 /var/task/node_modules/extsprintf
> json-schema@0.2.3 /var/task/node_modules/json-schema
> verror@1.10.0 /var/task/node_modules/verror
> core-util-is@1.0.2 /var/task/node_modules/core-util-is
> sshpk@1.16.1 /var/task/node_modules/sshpk
> asn1@0.2.4 /var/task/node_modules/asn1
> bcrypt-pbkdf@1.0.2 /var/task/node_modules/bcrypt-pbkdf
> tweetnacl@0.14.5 /var/task/node_modules/tweetnacl
> dashdash@1.14.1 /var/task/node_modules/dashdash
> ecc-jsbn@0.1.2 /var/task/node_modules/ecc-jsbn
> jsbn@0.1.1 /var/task/node_modules/jsbn
> getpass@0.1.7 /var/task/node_modules/getpass
> is-typedarray@1.0.0 /var/task/node_modules/is-typedarray
> isstream@0.1.2 /var/task/node_modules/isstream
> json-stringify-safe@5.0.1 /var/task/node_modules/json-stringify-safe
> oauth-sign@0.9.0 /var/task/node_modules/oauth-sign
> performance-now@2.1.0 /var/task/node_modules/performance-now
> qs@6.5.2 /var/task/node_modules/qs
> safe-buffer@5.1.2 /var/task/node_modules/safe-buffer
> tough-cookie@2.4.3 /var/task/node_modules/request/node_modules/tough-cookie
> psl@1.1.31 /var/task/node_modules/psl
> punycode@1.4.1 /var/task/node_modules/request/node_modules/punycode
> tunnel-agent@0.6.0 /var/task/node_modules/tunnel-agent
> uuid@3.3.2 /var/task/node_modules/uuid
> request-promise-native@1.0.7 /var/task/node_modules/request-promise-native
> request-promise-core@1.1.2 /var/task/node_modules/request-promise-core
> lodash@4.17.15 /var/task/node_modules/lodash
> stealthy-require@1.1.1 /var/task/node_modules/stealthy-require
> tough-cookie@2.5.0 /var/task/node_modules/tough-cookie
> sax@1.2.4 /var/task/node_modules/sax
> symbol-tree@3.2.2 /var/task/node_modules/symbol-tree
> w3c-hr-time@1.0.1 /var/task/node_modules/w3c-hr-time
> browser-process-hrtime@0.1.3 /var/task/node_modules/browser-process-hrtime
> whatwg-url@6.5.0 /var/task/node_modules/whatwg-url
> ws@5.2.2 /var/task/node_modules/ws
> async-limiter@1.0.0 /var/task/node_modules/async-limiter
> xml-name-validator@3.0.0 /var/task/node_modules/xml-name-validator
> mathjax@2.7.5 /var/task/node_modules/mathjax
> svg2png@4.1.1 /var/task/node_modules/svg2png
> file-url@2.0.2 /var/task/node_modules/file-url
> phantomjs-prebuilt@2.1.16 /var/task/node_modules/phantomjs-prebuilt
> es6-promise@4.2.6 /var/task/node_modules/es6-promise
> extract-zip@1.6.7 /var/task/node_modules/extract-zip
> concat-stream@1.6.2 /var/task/node_modules/concat-stream
> buffer-from@1.1.1 /var/task/node_modules/buffer-from
> inherits@2.0.3 /var/task/node_modules/inherits
> readable-stream@2.3.6 /var/task/node_modules/readable-stream
> isarray@1.0.0 /var/task/node_modules/isarray
> process-nextick-args@2.0.0 /var/task/node_modules/process-nextick-args
> string_decoder@1.1.1 /var/task/node_modules/string_decoder
> util-deprecate@1.0.2 /var/task/node_modules/util-deprecate
> typedarray@0.0.6 /var/task/node_modules/typedarray
> debug@2.6.9 /var/task/node_modules/debug
> ms@2.0.0 /var/task/node_modules/ms
> mkdirp@0.5.1 /var/task/node_modules/mkdirp
> minimist@0.0.8 /var/task/node_modules/minimist
> yauzl@2.4.1 /var/task/node_modules/yauzl
> fd-slicer@1.0.1 /var/task/node_modules/fd-slicer
> pend@1.2.0 /var/task/node_modules/pend
> fs-extra@1.0.0 /var/task/node_modules/fs-extra
> graceful-fs@4.1.15 /var/task/node_modules/graceful-fs
> jsonfile@2.4.0 /var/task/node_modules/jsonfile
> klaw@1.3.1 /var/task/node_modules/klaw
> hasha@2.2.0 /var/task/node_modules/hasha
> is-stream@1.1.0 /var/task/node_modules/is-stream
> pinkie-promise@2.0.1 /var/task/node_modules/pinkie-promise
> pinkie@2.0.4 /var/task/node_modules/pinkie
> kew@0.7.0 /var/task/node_modules/kew
> progress@1.1.8 /var/task/node_modules/progress
> request-progress@2.0.1 /var/task/node_modules/request-progress
> throttleit@1.0.0 /var/task/node_modules/throttleit
> which@1.3.1 /var/task/node_modules/which
> isexe@2.0.0 /var/task/node_modules/isexe
> yargs@6.6.0 /var/task/node_modules/yargs
> camelcase@3.0.0 /var/task/node_modules/camelcase
> cliui@3.2.0 /var/task/node_modules/cliui
> string-width@1.0.2 /var/task/node_modules/string-width
> code-point-at@1.1.0 /var/task/node_modules/code-point-at
> is-fullwidth-code-point@1.0.0 /var/task/node_modules/string-width/node_modules/is-fullwidth-code-point
> number-is-nan@1.0.1 /var/task/node_modules/number-is-nan
> strip-ansi@3.0.1 /var/task/node_modules/strip-ansi
> ansi-regex@2.1.1 /var/task/node_modules/ansi-regex
> wrap-ansi@2.1.0 /var/task/node_modules/wrap-ansi
> decamelize@1.2.0 /var/task/node_modules/decamelize
> get-caller-file@1.0.3 /var/task/node_modules/get-caller-file
> os-locale@1.4.0 /var/task/node_modules/os-locale
> lcid@1.0.0 /var/task/node_modules/lcid
> invert-kv@1.0.0 /var/task/node_modules/invert-kv
> read-pkg-up@1.0.1 /var/task/node_modules/read-pkg-up
> find-up@1.1.2 /var/task/node_modules/find-up
> path-exists@2.1.0 /var/task/node_modules/path-exists
> read-pkg@1.1.0 /var/task/node_modules/read-pkg
> load-json-file@1.1.0 /var/task/node_modules/load-json-file
> parse-json@2.2.0 /var/task/node_modules/parse-json
> error-ex@1.3.2 /var/task/node_modules/error-ex
> is-arrayish@0.2.1 /var/task/node_modules/is-arrayish
> pify@2.3.0 /var/task/node_modules/pify
> strip-bom@2.0.0 /var/task/node_modules/strip-bom
> is-utf8@0.2.1 /var/task/node_modules/is-utf8
> normalize-package-data@2.5.0 /var/task/node_modules/normalize-package-data
> hosted-git-info@2.7.1 /var/task/node_modules/hosted-git-info
> resolve@1.10.1 /var/task/node_modules/resolve
> path-parse@1.0.6 /var/task/node_modules/path-parse
> semver@5.7.0 /var/task/node_modules/semver
> validate-npm-package-license@3.0.4 /var/task/node_modules/validate-npm-package-license
> spdx-correct@3.1.0 /var/task/node_modules/spdx-correct
> spdx-expression-parse@3.0.0 /var/task/node_modules/spdx-expression-parse
> spdx-exceptions@2.2.0 /var/task/node_modules/spdx-exceptions
> spdx-license-ids@3.0.4 /var/task/node_modules/spdx-license-ids
> path-type@1.1.0 /var/task/node_modules/path-type
> require-directory@2.1.1 /var/task/node_modules/require-directory
> require-main-filename@1.0.1 /var/task/node_modules/require-main-filename
> set-blocking@2.0.0 /var/task/node_modules/set-blocking
> which-module@1.0.0 /var/task/node_modules/which-module
> y18n@3.2.1 /var/task/node_modules/y18n
> yargs-parser@4.2.1 /var/task/node_modules/yargs-parser
> source-map@0.6.1 /var/task/node_modules/source-map

`make package PACKAGE_PROFILE=default PACKAGE_BUCKET=my-bucket-name` output:

> /bin/sh: 1: [[: not found
> Dependencies for layer mathjax-node-layer are not installed, run make layers first!
> make: *** [Makefile:22: ensure-layer-mathjax-node-layer] Error 1

@fquffio: make layers works without errors, but I get this error on running make package.

**Comment by kanujbhatnagar** [comment]
@fquffio any thoughts on what might be causing this error?

**Comment by kanujbhatnagar** [comment]
Anyone else getting this error:

`/bin/sh: 1: [[: not found
Dependencies for layer mathjax-node-layer are not installed, run make layers first!
make: *** [Makefile:22: ensure-layer-mathjax-node-layer] Error 1`

should just write the following at the top of the Makefile:

`SHELL := /bin/bash # Use bash syntax`

credit: [SO answer](https://askubuntu.com/a/625702/976498)
